### ISSUE TITLE
[moment] input_format not validate

### ISSUE THREAD

**Issue by huangciyin** [stephenhandley/graphql-validated-types#3]
https://github.com/stephenhandley/graphql-validated-types/blob/master/src/GraphQLValidatedMoment.js#L12

see source code above, format not checked, input_format validate not work.

**Comment by stephenhandley** [comment]
@huangciyin Thanks for the heads up and sorry for the delay on this, I will try to get to it this week or over the weekend.

**Comment by stephenhandley** [comment]
See this test case showing working format validation: 
https://github.com/stephenhandley/graphql-validated-types/blob/master/src/GraphQLValidatedMoment.test.js#L38-L64

If you're still having issues please open another ticket with a more detailed description of the issues.
