### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by LennyPenny** [stephenhandley/graphql-validated-types#4]
Is there an example anywhere using this in on an actual Schema? 
Would love to see how it interacts with schema definitions

**Comment by stephenhandley** [comment]
Hey @LennyPenny sorry been busy with work, but finally got an opportunity to put together example app. See /example

You can run locally by doing 
```
git clone https://github.com/stephenhandley/graphql-validated-types
cd graphql-validated-types
npm run example
```
