### ISSUE TITLE
Assignment of const / read-only variable 

### ISSUE THREAD

**Issue by zolero** [stephenhandley/graphql-validated-types#8]
Attempt to assign to const or read-only variable in latest version of GraphQL. Removing this line fixed the validation for me.

On this line: 
https://github.com/stephenhandley/graphql-validated-types/blob/390a43dbc00f7257a1b2e4e796623a9d2f74b6e3/src/GraphQLValidatedScalar.js#L59

"graphql": "^15.0.0",

**Comment by stephenhandley** [comment]
thx @zolero just pushed changes and published `2.8.0` to npm that should solve this, let me know if that works for you
